# пример запуска скрипта docker compose -f docker-compose.prod.yml -p rsp-prod up

networks:
  prod:

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile.prod
    container_name: prod-mod
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    # volumes:
    #   - './nginx/rsp.conf:/etc/nginx/sites-available/rsp.conf'
    #   - './nginx.conf:/etc/nginx/nginx.conf'
    #   - '/etc/letsencrypt/:/etc/letsencrypt/'
    networks:
      - prod